CapstoneBackEnd: CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel Class Reference
CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel Class Reference
Public Member Functions
List< EntityAnnotation > CallGoogleVisionAPI ()
List< EntityAnnotation > CallGoogleVisionTags ()
List< EntityAnnotation > CallGoogleVisionOCR ()
Properties
string path [get, set]
string type [get, set]
Member Function Documentation
CallGoogleVisionAPI()
List< EntityAnnotation > CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionAPI ()
References CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionOCR(), CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionTags(), and CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.type.
CallGoogleVisionOCR()
List< EntityAnnotation > CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionOCR ()
References CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.path.
Referenced by CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionAPI().
CallGoogleVisionTags()
List< EntityAnnotation > CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionTags ()
References CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.path.
Referenced by CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionAPI().
Property Documentation
path
string CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.path get set
Referenced by CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionOCR(), and CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionTags().
type
string CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.type get set
Referenced by CapstoneBackEndAPI.ViewModels.GoogleVisionViewModel.CallGoogleVisionAPI().
The documentation for this class was generated from the following file:
/Users/robertpeters/CompSci/4970 Capstone/Capstone-BackEnd/CapstoneBackEndAPI/CapstoneBackEndAPI/ViewModels/GoogleVisionViewModel.cs